version: '3.1'

networks:
  net:

services:
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/datadeploy:
    networks:
      net:
        aliases:
          - postgres
    # resources:
    #   limits:
    #     memory: '1.5GB'
    #     cpus: '0.4'

  web:
    image: chores
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/var/app
    networks:
      net:
        aliases:
          - web
    # deploy:
    #   resources:
    #     limits:
    #       memory: '0.6GB'
    #       cpus: '0.3'

  nginx:
    image: nginx
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9999:80
    depends_on:
      - web
    networks:
      net:
        aliases:
          - nginx
    # deploy:
    #   resources:
    #     limits:
    #       memory: '0.1GB'
    #       cpus: '0.1'

volumes:
  postgres_data:
