version: '3.1'

networks:
  net:

services:
  postgres:
    image: postgres:alpine
    networks:
      net:
        aliases:
          - postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # deploy:
    #   resources:
    #     limits:
    #       memory: '1.5GB'
    #       cpus: '0.4'

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    restart: always
    command: start-dev --log-level=DEBUG --proxy passthrough --hostname-strict=false
    env_file:
      - .env
    ports:
      - 8080:4000
    depends_on:
      - postgres
    networks:
      net:
        aliases:
          - keycloak

  web:
    image: chores
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/var/app
    networks:
      net:
        aliases:
          - web
    # deploy:
    #   resources:
    #     limits:
    #       memory: '0.6GB'
    #       cpus: '0.3'

  nginx:
    image: nginx
    command: ["nginx-debug", "-g", "daemon off;"]
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - web
    networks:
      net:
        aliases:
          - nginx
    # deploy:
    #   resources:
    #     limits:
    #       memory: '0.1GB'
    #       cpus: '0.1'

volumes:
  postgres_data:
