default: &default
  adapter   : postgresql
  encoding  : unicode
  host      : <%= Rails.application.credentials.database[:host] %>
  username  : <%= Rails.application.credentials.database[:username] %>
  password  : <%= Rails.application.credentials.database[:password] %>
  database  : <%= Rails.application.credentials.database[:database] %>
  port      : <%= Rails.application.credentials.database[:port] %>

development:
  <<: *default
  # host      : 127.0.0.1
  # port      : 5433
  database  : <%= "#{Rails.application.credentials.database[:database]}_development" %>

test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: storage/test.sqlite3

production:
  <<: *default
  database  : <%= "#{Rails.application.credentials.database[:database]}" %>
