default: &default
  adapter   : postgresql
  encoding  : unicode
  host      : <%= Rails.application.credentials.database[:host] %>
  username  : <%= Rails.application.credentials.database[:username] %>
  password  : <%= Rails.application.credentials.database[:password] %>
  database  : <%= Rails.application.credentials.database[:database] %>
  port      : <%= Rails.application.credentials.database[:port] %>

development:
  <<: *default
  database  : <%= "#{Rails.application.credentials.database[:database]}_development" %>

test:
  <<: *default
  database  : <%= "#{Rails.application.credentials.database[:database]}_test" %>

production:
  <<: *default
  database  : <%= "#{Rails.application.credentials.database[:database]}" %>
